// Requirement catalogue — verbatim from the PV Quality System gap assessment specification.
// 57 requirements across 12 domains. Do not reword: these are the assessed control statements.

export type GapItem = {
  /** Requirement reference, e.g. "1.1" */
  ref: string;
  /** Domain heading */
  d: string;
  /** The requirement statement being assessed */
  req: string;
  /** Regulatory reference */
  reg: string;
  /** Evidence required to substantiate a score */
  ev: string;
};

export const GAP_ITEMS: GapItem[] = [
  {
    ref: "1.1",
    d: "1. PV System Governance & QPPV",
    req: "A named QPPV (or local person responsible for PV) is formally appointed, resident in-country, contactable 24/7, and notified to NAFDAC.",
    reg: "NAFDAC RDQP-034-00; GVP Module I",
    ev: "Appointment letter; CV; NAFDAC notification correspondence; 24/7 contact details",
  },
  {
    ref: "1.2",
    d: "1. PV System Governance & QPPV",
    req: "A deputy / back-up QPPV is formally appointed with documented delegation covering absence.",
    reg: "NAFDAC RDQP-034-00; GVP Module I",
    ev: "Deputy appointment letter; delegation of authority document",
  },
  {
    ref: "1.3",
    d: "1. PV System Governance & QPPV",
    req: "An organisational chart defines PV reporting lines and the interface with commercial, regulatory and quality functions.",
    reg: "GVP Module I",
    ev: "Current org chart with version date",
  },
  {
    ref: "1.4",
    d: "1. PV System Governance & QPPV",
    req: "Job descriptions setting out PV responsibilities exist for every role with PV duties, including field-facing roles.",
    reg: "GVP Module I",
    ev: "Signed job descriptions for QPPV, PV staff, medical reps, distributor liaison",
  },
  {
    ref: "1.5",
    d: "1. PV System Governance & QPPV",
    req: "Management reviews PV system performance at a defined frequency against agreed metrics, with documented minutes and actions.",
    reg: "GVP Module I",
    ev: "Management review agenda, minutes, KPI pack, action log",
  },
  {
    ref: "2.1",
    d: "2. Pharmacovigilance System Master File",
    req: "A PSMF exists and accurately describes the pharmacovigilance system actually in operation.",
    reg: "GVP Module II",
    ev: "Current PSMF with approval signatures",
  },
  {
    ref: "2.2",
    d: "2. Pharmacovigilance System Master File",
    req: "PSMF annexes are complete: QPPV CV and JD, SOP list, contracts/SDEAs, computerised systems, audit schedule, deviations.",
    reg: "GVP Module II",
    ev: "PSMF Annexes A–H",
  },
  {
    ref: "2.3",
    d: "2. Pharmacovigilance System Master File",
    req: "A PSMF logbook records all changes with version numbers, effective dates and rationale.",
    reg: "GVP Module II",
    ev: "PSMF change logbook",
  },
  {
    ref: "2.4",
    d: "2. Pharmacovigilance System Master File",
    req: "The PSMF is kept current and can be produced for inspection at short notice.",
    reg: "GVP Modules II & III",
    ev: "Retrieval test record; location and access procedure",
  },
  {
    ref: "3.1",
    d: "3. SOPs & Document Control",
    req: "Controlled SOPs cover the full PV lifecycle: intake, triage, data entry, assessment, follow-up, submission, archiving.",
    reg: "NAFDAC RDQP-034-00; GVP Module I",
    ev: "SOP index mapped to lifecycle stages",
  },
  {
    ref: "3.2",
    d: "3. SOPs & Document Control",
    req: "SOPs are version-controlled, formally approved, dated, and subject to scheduled periodic review.",
    reg: "GVP Module I",
    ev: "SOP cover pages; review schedule; approval records",
  },
  {
    ref: "3.3",
    d: "3. SOPs & Document Control",
    req: "Only the current effective version is accessible to users; superseded versions are withdrawn from circulation.",
    reg: "GVP Module I",
    ev: "Document register; withdrawal records",
  },
  {
    ref: "3.4",
    d: "3. SOPs & Document Control",
    req: "Read-and-understood records exist for every relevant SOP, for every relevant role.",
    reg: "GVP Module I",
    ev: "Signed read-and-understood log or LMS record",
  },
  {
    ref: "3.5",
    d: "3. SOPs & Document Control",
    req: "Simplified job aids / working practice documents exist for field-facing roles who will not read a full SOP.",
    reg: "NAFDAC RDQP-034-00",
    ev: "One-page job aids for reps, distributors, pharmacists, PMVs",
  },
  {
    ref: "4.1",
    d: "4. Case Intake & Source Management",
    req: "Every intake channel is formally defined and documented: phone, WhatsApp, email, field representative, distributor, portal, social media, product complaints.",
    reg: "GVP Module VI",
    ev: "Documented channel inventory with owners",
  },
  {
    ref: "4.2",
    d: "4. Case Intake & Source Management",
    req: "Each intake channel has a named owner and a defined checking frequency, including weekends and public holidays.",
    reg: "GVP Module VI",
    ev: "Channel monitoring rota; coverage plan",
  },
  {
    ref: "4.3",
    d: "4. Case Intake & Source Management",
    req: "A written agreement defines PV obligations for every distributor, affiliate and third party feeding information into the company.",
    reg: "GVP Module I; Module VI",
    ev: "Executed SDEAs / PV clauses in distribution agreements",
  },
  {
    ref: "4.4",
    d: "4. Case Intake & Source Management",
    req: "Field staff and affiliates forward safety information to PV within a defined maximum timeframe (e.g. 24 hours of awareness).",
    reg: "GVP Module VI",
    ev: "SOP-defined timeframe; sample forwarding records with timestamps",
  },
  {
    ref: "4.5",
    d: "4. Case Intake & Source Management",
    req: "Solicited sources (market research, patient support programmes, digital media) are identified and handled under a distinct workflow.",
    reg: "GVP Module VI",
    ev: "Solicited source register; dedicated workflow",
  },
  {
    ref: "4.6",
    d: "4. Case Intake & Source Management",
    req: "Documented evidence exists that intake channels are actively monitored, not merely available.",
    reg: "GVP Modules I & VI",
    ev: "Channel check logs; inbox reconciliation records; screenshots",
  },
  {
    ref: "5.1",
    d: "5. Case Tracking & Duplicate Detection",
    req: "A single central register captures every incoming safety report, regardless of channel or source.",
    reg: "GVP Module VI",
    ev: "Intake register covering all channels for the review period",
  },
  {
    ref: "5.2",
    d: "5. Case Tracking & Duplicate Detection",
    req: "Each report receives a unique sequential case identifier at the point of receipt, before triage.",
    reg: "GVP Module VI",
    ev: "Case numbering convention; register showing unbroken sequence",
  },
  {
    ref: "5.3",
    d: "5. Case Tracking & Duplicate Detection",
    req: "A documented duplicate-detection method exists with defined match criteria applied to every case.",
    reg: "GVP Module VI",
    ev: "Duplicate check SOP; evidence of checks performed",
  },
  {
    ref: "5.4",
    d: "5. Case Tracking & Duplicate Detection",
    req: "Periodic reconciliation is performed between the intake register, product complaint handling, medical information and partner databases.",
    reg: "GVP Modules I & VI",
    ev: "Reconciliation records with discrepancy resolution",
  },
  {
    ref: "6.1",
    d: "6. ICSR Processing & Regulatory Submission",
    req: "The four minimum validity criteria are applied and the outcome documented for every report received.",
    reg: "GVP Module VI",
    ev: "Validity assessment recorded on each case",
  },
  {
    ref: "6.2",
    d: "6. ICSR Processing & Regulatory Submission",
    req: "Day 0 is defined in procedure and recorded consistently across all channels and sources.",
    reg: "GVP Module VI",
    ev: "SOP definition; register showing Day 0 per case",
  },
  {
    ref: "6.3",
    d: "6. ICSR Processing & Regulatory Submission",
    req: "A follow-up procedure defines the number of attempts, timing, method and documentation for incomplete reports.",
    reg: "GVP Module VI",
    ev: "Follow-up SOP; sample follow-up correspondence",
  },
  {
    ref: "6.4",
    d: "6. ICSR Processing & Regulatory Submission",
    req: "Seriousness, expectedness and causality are assessed by an appropriately qualified person against a defined reference safety document.",
    reg: "GVP Module VI",
    ev: "Assessment records; reference safety information; assessor qualifications",
  },
  {
    ref: "6.5",
    d: "6. ICSR Processing & Regulatory Submission",
    req: "Serious ICSRs are submitted to NAFDAC within 15 calendar days and non-serious reports within the required timeframe.",
    reg: "NAFDAC RDQP-034-00; GVP Module VI",
    ev: "Submission acknowledgements; timeliness report for review period",
  },
  {
    ref: "6.6",
    d: "6. ICSR Processing & Regulatory Submission",
    req: "Submission timeliness is measured, trended, and escalated to management when targets are missed.",
    reg: "GVP Module I",
    ev: "Timeliness KPI trend; escalation records",
  },
  {
    ref: "7.1",
    d: "7. Signal & Risk Management",
    req: "A documented signal detection process proportionate to case volume and product portfolio is in place.",
    reg: "GVP Module IX",
    ev: "Signal management SOP; detection method rationale",
  },
  {
    ref: "7.2",
    d: "7. Signal & Risk Management",
    req: "Signals are recorded, validated, prioritised and tracked to documented closure.",
    reg: "GVP Module IX",
    ev: "Signal tracking log with closure records",
  },
  {
    ref: "7.3",
    d: "7. Signal & Risk Management",
    req: "Risk management planning and risk minimisation measures are defined where required for the portfolio.",
    reg: "GVP Modules V & XVI",
    ev: "RMPs; risk minimisation materials; effectiveness measures",
  },
  {
    ref: "7.4",
    d: "7. Signal & Risk Management",
    req: "A procedure exists for urgent safety action: restrictions, recalls, and Dear Healthcare Professional communications.",
    reg: "GVP Module XV",
    ev: "Urgent safety SOP; recall interface with QA; contact cascade",
  },
  {
    ref: "8.1",
    d: "8. Aggregate Reporting & Literature",
    req: "A PSUR/PBRER schedule is maintained against NAFDAC requirements and international birth dates.",
    reg: "NAFDAC RDQP-034-00; GVP Module VII",
    ev: "Aggregate reporting schedule; submission history",
  },
  {
    ref: "8.2",
    d: "8. Aggregate Reporting & Literature",
    req: "A documented procedure governs compilation, medical review, approval and archiving of aggregate reports.",
    reg: "GVP Module VII",
    ev: "Aggregate report SOP; approved reports with sign-off",
  },
  {
    ref: "8.3",
    d: "8. Aggregate Reporting & Literature",
    req: "Scientific literature is screened at a defined frequency using a documented search strategy, with results retained.",
    reg: "GVP Module VI",
    ev: "Search strategy; screening records; retained hits",
  },
  {
    ref: "9.1",
    d: "9. Training & Competency",
    req: "A role-specific PV training curriculum exists, differentiated for internal staff, medical representatives, distributors, community pharmacists, patent medicine vendors and physicians.",
    reg: "NAFDAC RDQP-034-00; GVP Module I",
    ev: "Curriculum matrix mapping role to module and depth",
  },
  {
    ref: "9.2",
    d: "9. Training & Competency",
    req: "PV induction training is completed before any individual undertakes PV-relevant duties.",
    reg: "GVP Module I",
    ev: "Induction records with dates preceding first duty",
  },
  {
    ref: "9.3",
    d: "9. Training & Competency",
    req: "Refresher training is delivered at a defined frequency and after significant process or regulatory change.",
    reg: "GVP Module I",
    ev: "Refresher schedule and completion records",
  },
  {
    ref: "9.4",
    d: "9. Training & Competency",
    req: "Competency is assessed and evidenced, not inferred from attendance, with defined pass criteria and remediation.",
    reg: "GVP Module I",
    ev: "Assessment instrument; scored results; remediation records",
  },
  {
    ref: "9.5",
    d: "9. Training & Competency",
    req: "A central training matrix records status for every individual with PV duties, including external affiliates, and is inspection-ready.",
    reg: "GVP Modules I & III",
    ev: "Consolidated training matrix covering internal and external personnel",
  },
  {
    ref: "10.1",
    d: "10. Quality Management, CAPA & Inspection Readiness",
    req: "A documented quality management system covers pharmacovigilance, with stated quality objectives and monitored KPIs.",
    reg: "NAFDAC RDQP-034-00; GVP Module I",
    ev: "PV quality manual; KPI definitions and current results",
  },
  {
    ref: "10.2",
    d: "10. Quality Management, CAPA & Inspection Readiness",
    req: "Deviations and non-conformances are recorded, investigated and root-caused within defined timelines.",
    reg: "GVP Module I",
    ev: "Deviation log; investigation reports",
  },
  {
    ref: "10.3",
    d: "10. Quality Management, CAPA & Inspection Readiness",
    req: "A CAPA process operates with assigned ownership, due dates, effectiveness checks and formal closure.",
    reg: "GVP Module I",
    ev: "CAPA log with effectiveness verification records",
  },
  {
    ref: "10.4",
    d: "10. Quality Management, CAPA & Inspection Readiness",
    req: "A risk-based internal audit programme covers the PV system and its affiliates and third parties.",
    reg: "GVP Module IV",
    ev: "Audit programme; audit reports; follow-up actions",
  },
  {
    ref: "10.5",
    d: "10. Quality Management, CAPA & Inspection Readiness",
    req: "An independent or external audit of the PV quality system has been performed at a defined interval.",
    reg: "GVP Module IV",
    ev: "External audit report and CAPA response",
  },
  {
    ref: "10.6",
    d: "10. Quality Management, CAPA & Inspection Readiness",
    req: "Inspection readiness is established: procedure, trained front room and back room, document retrieval capability, and a completed mock inspection.",
    reg: "GVP Module III",
    ev: "Inspection readiness SOP; mock inspection report; retrieval test results",
  },
  {
    ref: "11.1",
    d: "11. Partners, Vendors & Agreements",
    req: "Safety data exchange agreements are executed with all licensors, partners, distributors and service providers.",
    reg: "GVP Module I",
    ev: "Executed SDEA register with expiry and review dates",
  },
  {
    ref: "11.2",
    d: "11. Partners, Vendors & Agreements",
    req: "SDEAs specify exchange timelines, named contacts, reconciliation frequency, audit rights and breach handling.",
    reg: "GVP Module I",
    ev: "SDEA content review against checklist",
  },
  {
    ref: "11.3",
    d: "11. Partners, Vendors & Agreements",
    req: "Partners and vendors are qualified before use and periodically reassessed on a risk basis.",
    reg: "GVP Modules I & IV",
    ev: "Qualification records; reassessment schedule",
  },
  {
    ref: "11.4",
    d: "11. Partners, Vendors & Agreements",
    req: "Reconciliation with each partner is performed and documented at the frequency stated in the agreement.",
    reg: "GVP Module I",
    ev: "Reconciliation records for the review period",
  },
  {
    ref: "12.1",
    d: "12. Data, Systems & Business Continuity",
    req: "The safety data repository or database is fit for purpose with role-based, individually attributable access control.",
    reg: "GVP Modules I & VI",
    ev: "System description; user access list; access review records",
  },
  {
    ref: "12.2",
    d: "12. Data, Systems & Business Continuity",
    req: "Computerised systems used in PV are validated against documented user requirements, with testing evidence retained.",
    reg: "GVP Module I",
    ev: "Validation plan, test scripts, summary report",
  },
  {
    ref: "12.3",
    d: "12. Data, Systems & Business Continuity",
    req: "An audit trail is enabled, periodically reviewed, and protected from alteration or deletion.",
    reg: "GVP Module I",
    ev: "Audit trail configuration; review records",
  },
  {
    ref: "12.4",
    d: "12. Data, Systems & Business Continuity",
    req: "Data retention and archiving meet regulatory requirements, with secure and retrievable storage for the required period.",
    reg: "NAFDAC RDQP-034-00; GVP Module I",
    ev: "Retention schedule; archive location; retrieval test",
  },
  {
    ref: "12.5",
    d: "12. Data, Systems & Business Continuity",
    req: "A business continuity and disaster recovery plan covers loss of intake channels, personnel and the safety database, and has been tested.",
    reg: "GVP Module I",
    ev: "BCP/DR plan; test records",
  },
];

export const GAP_DOMAINS: string[] = [...new Set(GAP_ITEMS.map((i) => i.d))];
export const GAP_TOTAL = GAP_ITEMS.length;
