/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenewalsRouteImport } from './routes/renewals'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as CrmTasksRouteImport } from './routes/crm/tasks'
import { Route as CrmSettingsRouteImport } from './routes/crm/settings'
import { Route as CrmSearchRouteImport } from './routes/crm/search'
import { Route as CrmReportsRouteImport } from './routes/crm/reports'
import { Route as CrmPipelineRouteImport } from './routes/crm/pipeline'
import { Route as CrmNotesRouteImport } from './routes/crm/notes'
import { Route as CrmContactsRouteImport } from './routes/crm/contacts'
import { Route as CrmActivitiesRouteImport } from './routes/crm/activities'
import { Route as CrmEmailsIndexRouteImport } from './routes/crm/emails/index'
import { Route as CrmCompaniesIndexRouteImport } from './routes/crm/companies/index'
import { Route as CrmEmailsComposeRouteImport } from './routes/crm/emails/compose'
import { Route as CrmCompaniesIdRouteImport } from './routes/crm/companies/$id'

const RenewalsRoute = RenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmTasksRoute = CrmTasksRouteImport.update({
  id: '/crm/tasks',
  path: '/crm/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSettingsRoute = CrmSettingsRouteImport.update({
  id: '/crm/settings',
  path: '/crm/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSearchRoute = CrmSearchRouteImport.update({
  id: '/crm/search',
  path: '/crm/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmReportsRoute = CrmReportsRouteImport.update({
  id: '/crm/reports',
  path: '/crm/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/crm/pipeline',
  path: '/crm/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmNotesRoute = CrmNotesRouteImport.update({
  id: '/crm/notes',
  path: '/crm/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmActivitiesRoute = CrmActivitiesRouteImport.update({
  id: '/crm/activities',
  path: '/crm/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmEmailsIndexRoute = CrmEmailsIndexRouteImport.update({
  id: '/crm/emails/',
  path: '/crm/emails/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCompaniesIndexRoute = CrmCompaniesIndexRouteImport.update({
  id: '/crm/companies/',
  path: '/crm/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmEmailsComposeRoute = CrmEmailsComposeRouteImport.update({
  id: '/crm/emails/compose',
  path: '/crm/emails/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCompaniesIdRoute = CrmCompaniesIdRouteImport.update({
  id: '/crm/companies/$id',
  path: '/crm/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/opportunities': typeof OpportunitiesRoute
  '/renewals': typeof RenewalsRoute
  '/crm/activities': typeof CrmActivitiesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/notes': typeof CrmNotesRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/reports': typeof CrmReportsRoute
  '/crm/search': typeof CrmSearchRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/products/$id': typeof ProductsIdRoute
  '/crm/': typeof CrmIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/crm/companies/$id': typeof CrmCompaniesIdRoute
  '/crm/emails/compose': typeof CrmEmailsComposeRoute
  '/crm/companies/': typeof CrmCompaniesIndexRoute
  '/crm/emails/': typeof CrmEmailsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opportunities': typeof OpportunitiesRoute
  '/renewals': typeof RenewalsRoute
  '/crm/activities': typeof CrmActivitiesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/notes': typeof CrmNotesRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/reports': typeof CrmReportsRoute
  '/crm/search': typeof CrmSearchRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/products/$id': typeof ProductsIdRoute
  '/crm': typeof CrmIndexRoute
  '/products': typeof ProductsIndexRoute
  '/crm/companies/$id': typeof CrmCompaniesIdRoute
  '/crm/emails/compose': typeof CrmEmailsComposeRoute
  '/crm/companies': typeof CrmCompaniesIndexRoute
  '/crm/emails': typeof CrmEmailsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/opportunities': typeof OpportunitiesRoute
  '/renewals': typeof RenewalsRoute
  '/crm/activities': typeof CrmActivitiesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/notes': typeof CrmNotesRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/reports': typeof CrmReportsRoute
  '/crm/search': typeof CrmSearchRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/products/$id': typeof ProductsIdRoute
  '/crm/': typeof CrmIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/crm/companies/$id': typeof CrmCompaniesIdRoute
  '/crm/emails/compose': typeof CrmEmailsComposeRoute
  '/crm/companies/': typeof CrmCompaniesIndexRoute
  '/crm/emails/': typeof CrmEmailsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/opportunities'
    | '/renewals'
    | '/crm/activities'
    | '/crm/contacts'
    | '/crm/notes'
    | '/crm/pipeline'
    | '/crm/reports'
    | '/crm/search'
    | '/crm/settings'
    | '/crm/tasks'
    | '/products/$id'
    | '/crm/'
    | '/products/'
    | '/crm/companies/$id'
    | '/crm/emails/compose'
    | '/crm/companies/'
    | '/crm/emails/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/opportunities'
    | '/renewals'
    | '/crm/activities'
    | '/crm/contacts'
    | '/crm/notes'
    | '/crm/pipeline'
    | '/crm/reports'
    | '/crm/search'
    | '/crm/settings'
    | '/crm/tasks'
    | '/products/$id'
    | '/crm'
    | '/products'
    | '/crm/companies/$id'
    | '/crm/emails/compose'
    | '/crm/companies'
    | '/crm/emails'
  id:
    | '__root__'
    | '/'
    | '/opportunities'
    | '/renewals'
    | '/crm/activities'
    | '/crm/contacts'
    | '/crm/notes'
    | '/crm/pipeline'
    | '/crm/reports'
    | '/crm/search'
    | '/crm/settings'
    | '/crm/tasks'
    | '/products/$id'
    | '/crm/'
    | '/products/'
    | '/crm/companies/$id'
    | '/crm/emails/compose'
    | '/crm/companies/'
    | '/crm/emails/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  RenewalsRoute: typeof RenewalsRoute
  CrmActivitiesRoute: typeof CrmActivitiesRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmNotesRoute: typeof CrmNotesRoute
  CrmPipelineRoute: typeof CrmPipelineRoute
  CrmReportsRoute: typeof CrmReportsRoute
  CrmSearchRoute: typeof CrmSearchRoute
  CrmSettingsRoute: typeof CrmSettingsRoute
  CrmTasksRoute: typeof CrmTasksRoute
  ProductsIdRoute: typeof ProductsIdRoute
  CrmIndexRoute: typeof CrmIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  CrmCompaniesIdRoute: typeof CrmCompaniesIdRoute
  CrmEmailsComposeRoute: typeof CrmEmailsComposeRoute
  CrmCompaniesIndexRoute: typeof CrmCompaniesIndexRoute
  CrmEmailsIndexRoute: typeof CrmEmailsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/renewals': {
      id: '/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof RenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/tasks': {
      id: '/crm/tasks'
      path: '/crm/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof CrmTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/settings': {
      id: '/crm/settings'
      path: '/crm/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof CrmSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/search': {
      id: '/crm/search'
      path: '/crm/search'
      fullPath: '/crm/search'
      preLoaderRoute: typeof CrmSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/reports': {
      id: '/crm/reports'
      path: '/crm/reports'
      fullPath: '/crm/reports'
      preLoaderRoute: typeof CrmReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/notes': {
      id: '/crm/notes'
      path: '/crm/notes'
      fullPath: '/crm/notes'
      preLoaderRoute: typeof CrmNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/activities': {
      id: '/crm/activities'
      path: '/crm/activities'
      fullPath: '/crm/activities'
      preLoaderRoute: typeof CrmActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/emails/': {
      id: '/crm/emails/'
      path: '/crm/emails'
      fullPath: '/crm/emails/'
      preLoaderRoute: typeof CrmEmailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/companies/': {
      id: '/crm/companies/'
      path: '/crm/companies'
      fullPath: '/crm/companies/'
      preLoaderRoute: typeof CrmCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/emails/compose': {
      id: '/crm/emails/compose'
      path: '/crm/emails/compose'
      fullPath: '/crm/emails/compose'
      preLoaderRoute: typeof CrmEmailsComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/companies/$id': {
      id: '/crm/companies/$id'
      path: '/crm/companies/$id'
      fullPath: '/crm/companies/$id'
      preLoaderRoute: typeof CrmCompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  RenewalsRoute: RenewalsRoute,
  CrmActivitiesRoute: CrmActivitiesRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmNotesRoute: CrmNotesRoute,
  CrmPipelineRoute: CrmPipelineRoute,
  CrmReportsRoute: CrmReportsRoute,
  CrmSearchRoute: CrmSearchRoute,
  CrmSettingsRoute: CrmSettingsRoute,
  CrmTasksRoute: CrmTasksRoute,
  ProductsIdRoute: ProductsIdRoute,
  CrmIndexRoute: CrmIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  CrmCompaniesIdRoute: CrmCompaniesIdRoute,
  CrmEmailsComposeRoute: CrmEmailsComposeRoute,
  CrmCompaniesIndexRoute: CrmCompaniesIndexRoute,
  CrmEmailsIndexRoute: CrmEmailsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
